[package]
name = "issue277"
version = "0.0.0"
edition = "2021"
[lib]
name = "issue277"
path = "lib.rs"
crate-type = ["staticlib"]
[dependencies]
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
[profile.release]
panic = "abort"
opt-level = 2
